### ISSUE TITLE
MatplotlibWidget' object has no attribute '_dpi_ratio

### ISSUE THREAD

**Issue by xihajun** [rgerum/pylustrator#33]
Hi, thanks for your cool package. But I got some issues when try to run your example code using `python run_example.py` after pip install pylustrator.

```
  File "xxx/venv/lib/python3.7/site-packages/pylustrator/QComplexWidgets.py", line 1345, in icon
    pm.setDevicePixelRatio(self.canvas._dpi_ratio)
AttributeError: 'MatplotlibWidget' object has no attribute '_dpi_ratio'
```

Do you have any idea of solving this?

Many thanks,
Jun

**Comment by rgerum** [comment]
Hi, this is a problem I already solved some days ago with my last commit :-D But it is still in the current package version. I should do a bugfix release so that pylustrator can be used with the current matplotlib verison.
https://github.com/rgerum/pylustrator/commit/23ecf6718051b9d20227e97b25e490f3ff741deb

**Comment by rgerum** [comment]
I have released a new version. If you update the issue should be gone

**Comment by xihajun** [comment]
Thank you so much!
